# Generated by Django 6.0 on 2026-01-08 07:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, help_text="مثال: Bachelor's Degree in Computer Science", max_length=100),
        ),
        migrations.AddField(
            model_name='job',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='عدد سنوات الخبرة المطلوبة', null=True),
        ),
        migrations.AddField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="اللغات المطلوبة، مثال: ['Arabic', 'English']"),
        ),
        migrations.AddField(
            model_name='job',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list, help_text='مهارات إضافية مرغوبة (اختيارية)'),
        ),
        migrations.AddField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text="قائمة بالمهارات المطلوبة، مثال: ['Python', 'Django', 'PostgreSQL']"),
        ),
        migrations.AddField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL),
        ),
    ]
