# Generated by Django 6.0 on 2026-01-11 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0002_alter_job_options_job_education_level_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'ordering': ['-created_at'], 'verbose_name': 'Job', 'verbose_name_plural': 'Jobs'},
        ),
        migrations.AlterField(
            model_name='job',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Created At'),
        ),
        migrations.AlterField(
            model_name='job',
            name='description',
            field=models.TextField(verbose_name='Job Description'),
        ),
        migrations.AlterField(
            model_name='job',
            name='education_level',
            field=models.CharField(blank=True, help_text="e.g.: Bachelor's Degree in Computer Science", max_length=100, verbose_name='Education Level'),
        ),
        migrations.AlterField(
            model_name='job',
            name='employer',
            field=models.ForeignKey(limit_choices_to={'role': 'employer'}, on_delete=django.db.models.deletion.CASCADE, related_name='jobs', to=settings.AUTH_USER_MODEL, verbose_name='Employer'),
        ),
        migrations.AlterField(
            model_name='job',
            name='experience_years',
            field=models.PositiveIntegerField(blank=True, help_text='Required years of experience', null=True, verbose_name='Experience Years'),
        ),
        migrations.AlterField(
            model_name='job',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='job',
            name='languages',
            field=models.JSONField(blank=True, default=list, help_text="Required languages, e.g.: ['Arabic', 'English']", verbose_name='Languages'),
        ),
        migrations.AlterField(
            model_name='job',
            name='preferred_skills',
            field=models.JSONField(blank=True, default=list, help_text='Additional preferred skills (optional)', verbose_name='Preferred Skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='required_skills',
            field=models.JSONField(blank=True, default=list, help_text="List of required skills, e.g.: ['Python', 'Django', 'PostgreSQL']", verbose_name='Required Skills'),
        ),
        migrations.AlterField(
            model_name='job',
            name='title',
            field=models.CharField(max_length=255, verbose_name='Job Title'),
        ),
        migrations.AlterField(
            model_name='job',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Updated At'),
        ),
    ]
