# Generated by Django 5.2.10 on 2026-01-23 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0004_add_built_resume_models'),
        ('resumes', '0004_alter_resume_id'),
    ]

    operations = [
    ]
