# Generated by Django 5.2.10 on 2026-01-23 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0005_candidate_resume_profile'),
        ('resumes', '0006_alter_builtresume_id_alter_certification_id_and_more'),
    ]

    operations = [
    ]
