# Generated by Django 5.2.10 on 2026-01-24 15:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resumes', '0001_update_foreign_keys'),
        ('resumes', '0007_merge_20260123_2236'),
    ]

    operations = [
    ]
